### ISSUE TITLE
cnenlinter 好像有问题，lint 以后出现重复内容

### ISSUE THREAD

**Issue by HugeCH39** [selfteaching/markdown-writing-with-mixed-cn-en#4]
如题，见图

![image](https://user-images.githubusercontent.com/33472759/55683221-082eba00-5970-11e9-9e02-0a4248b37d9c.png)

![image](https://user-images.githubusercontent.com/33472759/55683231-1ed51100-5970-11e9-852b-52b2087aadb5.png)

**Comment by xiaolai** [comment]
改了。哈。
